qcom-common: unlock-us-gsm: include missing glibc header
Glibc removes sys/sysmacros.h which defines makedev from sys/types.h since v2.28.

Due to build error:
device/motorola/qcom-common/unlock-us-gsm/unlock-us-gsm.c:180: error: undefined reference to makedev

Change-Id: I306983e6f541eafc94e6374d115aea01682655b4