qcom-common: camerawrapper: add missing libs for headers
Due to build errors:
frameworks/native/include/binder/Parcel.h:23:10: fatal error: android-base/unique_fd.h file not found
frameworks/native/include/ui/ANativeObjectBase.h:22:10: fatal error: nativebase/nativebase.h file not found
frameworks/native/include/ui/Rect.h:28:10: fatal error: android/rect.h file not found
frameworks/native/include/gui/IGraphicBufferProducer.h:35:10: fatal error: hidl/HybridInterface.h file not found
frameworks/native/include/gui/IGraphicBufferProducer.h:36:10: fatal error: android/hardware/graphics/bufferqueue/1.0/IGraphicBufferProducer.h file not found

Change-Id: Ib1d9a03eb4d4bbd819c35b95eab14f8b795efb9c